extends: "pubnub"
rules:
  import/no-named-default: 0
  max-len: 0
  comma-dangle: 0
  no-else-return: 0
  no-param-reassign: 0
  prefer-rest-params: 0
  wrap-iife: 0
  no-underscore-dangle: 0
  import/no-extraneous-dependencies: 0
  class-methods-use-this: 0
globals:
  ng: true
  PubNub: true
  config: true
